### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by jmhelt**
I updated the people page to use Bootstrap 4 since they have existing functionality for grid layouts. This seemed better than needing to maintain our own CSS. You'll see that this greatly simplified the CSS in base.scss.

I also updated people.yml with all of Mike's previous advisees, so the people page should be up-to-date now.

### CODE REVIEW

**Comment by jmhelt** [comment]
You can see a preview of the new page [here](https://deploy-preview-3--awesome-heyrovsky-3e2ccc.netlify.com/).

**Comment by jmhelt** [comment]
Edit: I moved more of the site over to use bootstrap's grid other built-in css classes. This continues to shrink our CSS, so now most of it is just colors and fonts.

I'll add that another advantage of using bootstrap is that the people/home page works well on both mobile and desktop browsers, which you can see in the preview above.

**Comment by jmhelt** [comment]
Closing in favor of #4.

**Comment by alevy** [comment]
I personally dislike bootstrap and find it really difficult to maintain, but if you open this again, we'll switch over if you prefer it.

**Comment by jmhelt** [comment]
The new(ish) grid CSS attributes seem to provide comparable functionality to Bootstrap's grid, so I don't think it's necessary. And #4 fixes the original style issue that initially led me to Bootstrap.

**Pull request closed without merging**
